### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [system-ctl-global/waveAlign#44]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO section](https://github.com/FORARTfe/HyMPS#- ) \ [Treatments page](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Treatments.md#-- ) \ [Normalizing](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Treatments.md#normalizing-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/y-brehm/waveAlign)
(badge-generator URL: https://badgen.net/github/license/y-brehm/waveAlign)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by y-brehm** [comment]
Hey @forart! First of all, thank you for including us in your project!
We'll take care of the licence in the next few days!

**Comment by y-brehm** [comment]
Hi @MarcoRavich,
after careful consideration we decided to move the project to an organisational account and set it to private. You probably want to remove it from your project.
